/*
https://www.redblobgames.com/maps/mapgen4/
https://github.com/redblobgames/mapgen4/
https://github.com/redblobgames/1843-planet-generation
http://experilous.com/1/project/planet-generator/2014-09-28/planet-generator.js
http://bit-player.org/2011/a-slight-discrepancy
https://en.wikipedia.org/wiki/Voronoi_diagram
http://www-cs-students.stanford.edu/~amitp/game-programming/polygon-map-generation/
https://www.redblobgames.com/x/1929-voronoi-percolation/
https://www.complexity-explorables.org/explorables/baristas-secret/
*/